import 'package:get/get.dart';
import 'package:stylish_shop_app/models/product.dart';

class Productcontroller extends GetxController {
  var products = <Product>[].obs;

  @override
  void onInit() {
    super.onInit();
    loadproducts();
  }

  void loadproducts() {
    products.value = [
      Product(
        imageUrl: 'assets/images/facecreamjpeg.jpeg',
        description: 'Moisturizing face cream suitable for all skin types.',
        name: 'Face Cream',
        price: 199.0,
        category: 'Beauty',
        reviews: '120',
        specifications: '50ml, Dermatologically tested, Non-sticky formula',
      ),
      Product(
        imageUrl: 'assets/images/facewashjpeg.jpeg',
        description: 'Gentle face wash for clear and fresh skin.',
        name: 'Face Wash',
        price: 299.0,
        category: 'Beauty',
        reviews: '500',
        specifications: '100ml, Soap-free, Suitable for all skin types',
      ),
      Product(
        imageUrl: 'assets/images/facesoapjpeg.jpeg',
        description: 'Natural handmade face soap enriched with aloe vera.',
        name: 'Face Soap',
        price: 199.0,
        category: 'Beauty',
        reviews: '95',
        specifications: '75g, Handmade, Free from harsh chemicals',
      ),
      Product(
        imageUrl: 'assets/images/lipstick.jpeg',
        description: 'Matte long-lasting lipstick with vibrant colors.',
        name: 'Lipstick',
        price: 399.0,
        category: 'Beauty',
        reviews: '230',
        specifications: 'Waterproof, Smudge-proof, 12 shades available',
      ),
      Product(
        imageUrl: 'assets/images/eyeliner.webp',
        description: 'Waterproof eyeliner with precision tip.',
        name: 'Eyeliner',
        price: 249.0,
        category: 'Beauty',
        reviews: '310',
        specifications: 'Quick dry, Smudge proof, Easy application',
      ),
      Product(
        imageUrl: 'assets/images/serum.jpeg',
        description: 'Vitamin C serum for skin brightening.',
        name: 'Face Serum',
        price: 699.0,
        category: 'Beauty',
        reviews: '350',
        specifications: '30ml, Dermatologically tested, Paraben-free',
      ),

      // -------------------- FASHION (6) --------------------
      Product(
        imageUrl: 'assets/images/tshirtjpeg.jpeg',
        description: 'Comfortable cotton t-shirt for casual wear.',
        name: 'T-Shirt',
        price: 499.0,
        category: 'Fashion',
        reviews: '340',
        specifications: '100% Cotton, Machine washable, Multiple sizes',
      ),
      Product(
        imageUrl: 'assets/images/jacketjpeg.jpeg',
        description: 'Warm jacket perfect for winters.',
        name: 'Jacket',
        price: 1499.0,
        category: 'Fashion',
        reviews: '145',
        specifications: 'Polyester, Hooded, Zipper closure',
      ),
      Product(
        imageUrl: 'assets/images/jeansjpeg.jpeg',
        description: 'Durable jeans with a stylish fit.',
        name: 'Jeans',
        price: 999.0,
        category: 'Fashion',
        reviews: '310',
        specifications: 'Denim, Slim fit, Stretchable fabric',
      ),
      Product(
        imageUrl: 'assets/images/summerdress.jpeg',
        description: 'Floral summer dress for women.',
        name: 'Summer Dress',
        price: 899.0,
        category: 'Fashion',
        reviews: '210',
        specifications: 'Cotton blend, Available in multiple sizes',
      ),
      Product(
        imageUrl: 'assets/images/sunglasses.jpeg',
        description: 'Stylish sunglasses with UV protection.',
        name: 'Sunglasses',
        price: 599.0,
        category: 'Fashion',
        reviews: '180',
        specifications: 'UV 400, Lightweight, Unisex',
      ),
      Product(
        imageUrl: 'assets/images/handbag.jpeg',
        description: 'Trendy leather handbag.',
        name: 'Handbag',
        price: 1299.0,
        category: 'Fashion',
        reviews: '260',
        specifications: 'Leather finish, Multiple compartments',
      ),

      // -------------------- KIDS (6) --------------------
      Product(
        imageUrl: 'assets/images/kidstshirt.jpeg',
        description: 'Soft cotton t-shirt for kids.',
        name: 'Kids T-Shirt',
        price: 299.0,
        category: 'Kids',
        reviews: '90',
        specifications: '100% Cotton, Machine washable',
      ),
      Product(
        imageUrl: 'assets/images/kidsshoes.jpeg',
        description: 'Comfortable shoes for kids.',
        name: 'Kids Shoes',
        price: 499.0,
        category: 'Kids',
        reviews: '150',
        specifications: 'Lightweight, Non-slip sole',
      ),
      Product(
        imageUrl: 'assets/images/kidsfrock.jpeg',
        description: 'Cute frock for girls.',
        name: 'Kids Frock',
        price: 699.0,
        category: 'Kids',
        reviews: '130',
        specifications: 'Polyester, Soft lining, Available in colors',
      ),
      Product(
        imageUrl: 'assets/images/kidsjeans.jpeg',
        description: 'Stretchable jeans for kids.',
        name: 'Kids Jeans',
        price: 499.0,
        category: 'Kids',
        reviews: '100',
        specifications: 'Denim, Slim fit, Comfortable',
      ),
      Product(
        imageUrl: 'assets/images/kidsjacket.jpeg',
        description: 'Warm winter jacket for kids.',
        name: 'Kids Jacket',
        price: 799.0,
        category: 'Kids',
        reviews: '120',
        specifications: 'Wool blend, Hooded, Zipper closure',
      ),
      Product(
        imageUrl: 'assets/images/kidswatch.jpeg',
        description: 'Cartoon design digital watch.',
        name: 'Kids Watch',
        price: 249.0,
        category: 'Kids',
        reviews: '80',
        specifications: 'Digital, Waterproof, Fun design',
      ),

      // -------------------- MENS (6) --------------------
      Product(
        imageUrl: 'assets/images/shirtjpeg.jpeg',
        description: 'Formal shirt for office wear.',
        name: 'Formal Shirt',
        price: 799.0,
        category: 'Mens',
        reviews: '260',
        specifications: 'Cotton blend, Slim fit',
      ),
      Product(
        imageUrl: 'assets/images/tshirtjpeg.jpeg',
        description: 'Casual round neck t-shirt.',
        name: 'Mens T-Shirt',
        price: 499.0,
        category: 'Mens',
        reviews: '190',
        specifications: '100% Cotton, Regular fit',
      ),
      Product(
        imageUrl: 'assets/images/jeansjpeg.jpeg',
        description: 'Blue slim fit jeans.',
        name: 'Mens Jeans',
        price: 999.0,
        category: 'Mens',
        reviews: '230',
        specifications: 'Denim, Stretchable fabric',
      ),
      Product(
        imageUrl: 'assets/images/sneakersjpeg.jpeg',
        description: 'Casual sneakers for men.',
        name: 'Mens Sneakers',
        price: 1299.0,
        category: 'Mens',
        reviews: '310',
        specifications: 'Rubber sole, Breathable material',
      ),
      Product(
        imageUrl: 'assets/images/watchmen.jpeg',
        description: 'Analog wristwatch with leather strap.',
        name: 'Mens Watch',
        price: 1599.0,
        category: 'Mens',
        reviews: '200',
        specifications: 'Quartz, Waterproof, Stylish design',
      ),
      Product(
        imageUrl: 'assets/images/jacketjpeg.jpeg',
        description: 'Stylish bomber jacket.',
        name: 'Mens Jacket',
        price: 1799.0,
        category: 'Mens',
        reviews: '220',
        specifications: 'Polyester, Zipper, Slim fit',
      ),

      // -------------------- WOMENS (6) --------------------
      Product(
        imageUrl: 'assets/images/womenstop.jpeg',
        description: 'Trendy top for women.',
        name: 'Womens Top',
        price: 699.0,
        category: 'Womens',
        reviews: '180',
        specifications: 'Cotton blend, Regular fit',
      ),
      Product(
        imageUrl: 'assets/images/womenssaree.jpeg',
        description: 'Traditional saree for occasions.',
        name: 'Saree',
        price: 1499.0,
        category: 'Womens',
        reviews: '250',
        specifications: 'Silk blend, Lightweight',
      ),
      Product(
        imageUrl: 'assets/images/womenskurti.jpeg',
        description: 'Ethnic kurti with embroidery.',
        name: 'Kurti',
        price: 899.0,
        category: 'Womens',
        reviews: '210',
        specifications: 'Cotton, Hand-embroidered',
      ),
      Product(
        imageUrl: 'assets/images/womensjeans.jpeg',
        description: 'Skinny fit jeans for women.',
        name: 'Womens Jeans',
        price: 999.0,
        category: 'Womens',
        reviews: '190',
        specifications: 'Stretchable denim, Slim fit',
      ),
      Product(
        imageUrl: 'assets/images/handbag.jpeg',
        description: 'Premium handbag for women.',
        name: 'Womens Handbag',
        price: 1299.0,
        category: 'Womens',
        reviews: '300',
        specifications: 'PU Leather, Spacious compartments',
      ),
      Product(
        imageUrl: 'assets/images/womensheels.jpeg',
        description: 'Stylish heels for party wear.',
        name: 'Womens Heels',
        price: 1199.0,
        category: 'Womens',
        reviews: '160',
        specifications: 'Synthetic, Slip resistant',
      ),
    ];
  }
}
